import { createLogger } from '@medai/logger';
import PDFDocument from 'pdfkit';

const log = createLogger('pdf');

export interface ReportSection {
  heading: string;
  body: string;
}

export interface MedicalReportInput {
  title: string;
  patientName?: string;
  generatedAt?: Date;
  sections: ReportSection[];
  disclaimer?: string;
}

const DEFAULT_DISCLAIMER =
  'This document was generated by MedAI for informational purposes only and is not a ' +
  'substitute for professional medical advice, diagnosis, or treatment.';

/**
 * Render a medical report to a PDF Buffer. Uses PDFKit's built-in Helvetica
 * (no external font files), keeping it portable across the Bun runtime.
 */
export function generateMedicalReport(input: MedicalReportInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      doc.font('Helvetica-Bold').fontSize(20).fillColor('#0E9F6E').text(input.title);
      doc.moveDown(0.5);

      doc.font('Helvetica').fontSize(10).fillColor('#666666');
      doc.text(`Generated: ${(input.generatedAt ?? new Date()).toISOString()}`);
      if (input.patientName) {
        doc.text(`Patient: ${input.patientName}`);
      }

      doc.fillColor('#000000').moveDown();

      for (const section of input.sections) {
        doc.font('Helvetica-Bold').fontSize(14).text(section.heading);
        doc.moveDown(0.25);
        doc.font('Helvetica').fontSize(11).text(section.body, { align: 'left' });
        doc.moveDown();
      }

      doc.moveDown();
      doc
        .font('Helvetica-Oblique')
        .fontSize(8)
        .fillColor('#888888')
        .text(input.disclaimer ?? DEFAULT_DISCLAIMER);

      doc.end();
    } catch (err) {
      log.error({ err }, 'PDF generation failed');
      reject(err instanceof Error ? err : new Error(String(err)));
    }
  });
}
